[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:telegram-bot-api]
command=telegram-bot-api --api-id=%(ENV_API_ID)s --api-hash=%(ENV_API_HASH)s --local --http-port=8081 --dir=/app/tba_data
autorestart=true
startretries=5
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bot]
command=bash /app/start.sh
autorestart=true
priority=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
