[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:telegram-bot-api]
command=telegram-bot-api --api_id=%(ENV_API_ID)s --api_hash=%(ENV_API_HASH)s --local --http_port=8081 --dir=/app/downloads
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bot]
command=bash /app/start.sh
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
